version: '3.0'

networks:
  laravel_network:
    driver: bridge

volumes:
  db_server1_data:
    driver: local
  db_server2_data:
    driver: local
  db_server3_data:
    driver: local

services:
  # Servidor PostgreSQL
  db_server1:
    image: postgres:13
    container_name: db_server1
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - "5450:5432"
    volumes:
      - db_server1_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  # Servidor de MongoDB
  db_server2:
    image: mongo:latest
    container_name: db_server2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27020:27017"
    volumes:
      - db_server2_data:/data/db
    networks:
      - laravel_network

  # Servidor MySQL
  db_server3:
    image: mysql:8.0
    container_name: db_server3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - db_server3_data:/var/lib/mysql
    networks:
      - laravel_network
  
  # Servidor Auth
  auth-service:
      # dir local
    image: my-php-app  
    container_name: auth-service
    restart: unless-stopped
    volumes:
      - ./auth-service:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:ywmpbc5TT+QGUOPPlwUDwZJKqQUX0HqDFlh/uRsjh7c=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      # red interna
      - DB_HOST=db_server1
      - DB_PORT=5432
      - DB_DATABASE=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=Z7Pc4p6GurcEanHw3tOUjSmyvX1PzkzKp7R17Awkeu0wODoEfi9ci30pOlQpi7Go
    ports:
      - "8080:80"
    depends_on:
      - db_server1
    networks:
      - laravel_network

      # Servidor Inventory
  inventory-service:
      # dir local
    image: inventory-service  
    container_name: inventory-service
    restart: unless-stopped
    volumes:
      - ./inventory-service:/var/www/html
    environment:
      # puertos internos
      - MONGO_URI=mongodb://root:root@db_server2:27017/admin
      - APP_ENV=local
      - APP_KEY=base64:ywmpbc5TT+QGUOPPlwUDwZJKqQUX0HqDFlh/uRsjh7c=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - JWT_SECRET=Z7Pc4p6GurcEanHw3tOUjSmyvX1PzkzKp7R17Awkeu0wODoEfi9ci30pOlQpi7Go
    ports:
      - "8089:80"
    depends_on:
      - db_server2
    networks:
      - laravel_network
